application:
  subdomain: tubed
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://tubed:3000/

services:
  tubed:
    # upstream: ghcr.io/hst-sunday/tubed:0.2.3
    image: ghcr.io/hst-sunday/tubed:0.2.3
    user: nextjs:nodejs
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - AUTH_CODE={{.U.auth_code}}
      - JWT_SECRET={{ stable_secret "tubed#jwt" }}
    setup_script: |
      chown -R nextjs:nodejs /app/data /app/public/uploads /app/logs
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health
      interval: 30s
      timeout: 10s
