min_os_version: 1.3.8
name: Tubed
package: community.lazycat.app.tubed
version: 0.2.1
description: "一个图床服务、文件托管服务，适合在VPS上的简单存储服务"
homepage: https://github.com/hst-Sunday/tubed
author: hst-Sunday
application:
  subdomain: tubed
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://tubed:3000/

services:
  tubed:
    # ghcr.io/hst-sunday/tubed:0.2.1
    image: registry.lazycat.cloud/czyt/hst-sunday/tubed:bb7bf5a77bc14b92
    container_name: tubed
    user: nextjs:nodejs
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - AUTH_CODE={{.U.auth_code}}
      - JWT_SECRET={{ stable_secret "tubed#jwt" }}
    setup_script: |
      chown -R nextjs:nodejs /app/data /app/public/uploads /app/logs
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health
      interval: 30s
      timeout: 10s

locales:
  zh:
    name: "Tubed"
    description: "一个图床服务、文件托管服务，适合在VPS上的简单存储服务"
  en:
    name: "Tubed"
    description: "A image hosting service, file storage service, suitable for simple storage on a VPS"
